export interface Product {
  id: string;
  name: string;
  platform: 'Canva' | 'Notion' | 'Etsy';
  category: string;
  description: string;
  price: number;
  thumbnail: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 'canva-1',
    name: 'Ultimate Social Media Brand Kit',
    platform: 'Canva',
    category: 'Marketing',
    description: '100+ templates for Instagram, Facebook, and LinkedIn.',
    price: 47,
    thumbnail: 'https://picsum.photos/seed/brandkit/600/400',
  },
  {
    id: 'canva-2',
    name: 'Professional eBook Template',
    platform: 'Canva',
    category: 'Education',
    description: '50-page layout for lead magnets and digital books.',
    price: 29,
    thumbnail: 'https://picsum.photos/seed/ebook/600/400',
  },
  {
    id: 'canva-3',
    name: 'Webinar Slide Deck Pro',
    platform: 'Canva',
    category: 'Business',
    description: 'High-conversion presentation slides for online events.',
    price: 35,
    thumbnail: 'https://picsum.photos/seed/webinar/600/400',
  },
  {
    id: 'canva-4',
    name: 'Pinterest Viral Pin Bundle',
    platform: 'Canva',
    category: 'Social Media',
    description: 'Optimized templates for high click-through rates.',
    price: 19,
    thumbnail: 'https://picsum.photos/seed/pinterest/600/400',
  },
  {
    id: 'canva-5',
    name: 'YouTube Creator Pack',
    platform: 'Canva',
    category: 'Video',
    description: 'Thumbnails, channel art, and end screens.',
    price: 24,
    thumbnail: 'https://picsum.photos/seed/youtube/600/400',
  },
  {
    id: 'notion-1',
    name: 'Freelance OS',
    platform: 'Notion',
    category: 'Productivity',
    description: 'Complete workspace for managing clients, projects, and invoices.',
    price: 97,
    thumbnail: 'https://picsum.photos/seed/freelance/600/400',
  },
  {
    id: 'notion-2',
    name: 'Habit Tracker & Life Planner',
    platform: 'Notion',
    category: 'Lifestyle',
    description: 'Integrated system for daily habits and long-term goals.',
    price: 15,
    thumbnail: 'https://picsum.photos/seed/habit/600/400',
  },
  {
    id: 'notion-3',
    name: 'Content Calendar Master',
    platform: 'Notion',
    category: 'Marketing',
    description: 'Multi-platform content planning and scheduling system.',
    price: 39,
    thumbnail: 'https://picsum.photos/seed/content/600/400',
  },
  {
    id: 'notion-4',
    name: 'Student Success Dashboard',
    platform: 'Notion',
    category: 'Education',
    description: 'Academic planner with course notes and exam tracking.',
    price: 12,
    thumbnail: 'https://picsum.photos/seed/student/600/400',
  },
  {
    id: 'notion-5',
    name: 'Small Business CRM',
    platform: 'Notion',
    category: 'Business',
    description: 'Lightweight customer relationship management tool.',
    price: 49,
    thumbnail: 'https://picsum.photos/seed/crm/600/400',
  },
  {
    id: 'etsy-1',
    name: 'Ultimate Budget Planner',
    platform: 'Etsy',
    category: 'Finance',
    description: 'Printable monthly and yearly financial tracking sheets.',
    price: 9,
    thumbnail: 'https://picsum.photos/seed/budget/600/400',
  },
  {
    id: 'etsy-2',
    name: 'Meal Planner & Grocery System',
    platform: 'Etsy',
    category: 'Home',
    description: 'Weekly meal planning and categorized shopping lists.',
    price: 7,
    thumbnail: 'https://picsum.photos/seed/meal/600/400',
  },
  {
    id: 'etsy-3',
    name: 'Daily Gratitude Journal',
    platform: 'Etsy',
    category: 'Wellness',
    description: 'Minimalist morning and evening reflection prompts.',
    price: 8,
    thumbnail: 'https://picsum.photos/seed/gratitude/600/400',
  },
  {
    id: 'etsy-4',
    name: 'Fitness & Workout Tracker',
    platform: 'Etsy',
    category: 'Health',
    description: 'Comprehensive log for exercises, sets, and progress.',
    price: 10,
    thumbnail: 'https://picsum.photos/seed/fitness/600/400',
  },
  {
    id: 'etsy-5',
    name: 'Luxury Travel Itinerary',
    platform: 'Etsy',
    category: 'Travel',
    description: 'Elegant printable planner for trips and excursions.',
    price: 12,
    thumbnail: 'https://picsum.photos/seed/travel/600/400',
  },
];
